apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: "prometheus.your-ip-address.nip.io" # change with prometheus.your-ip-adress.nip.io (this comment is from me not from chatGPT)
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
            path: /
    - host: "grafana.your-ip-address.nip.io" # change with grafana.your-ip-adress.nip.io (this comment is from me not from chatGPT)
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
            path: /
