apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-tools-ingress
  namespace: devops-tools
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "jenkins.nip.io" # change with jenkins.your-ip-adress.nip.io (this comment is from me not from chatGPT)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080