apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-menu-server
  namespace: devops-tools
spec:
  project: default
  source:
    repoURL: https://github.com/ghaithsaidani/smart-menu-config
    targetRevision: HEAD
    path: k8s/charts/services/server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true