chart:
  name: smart-menu-client
replicaCount: 1

image:
  repository: smartmenuacr.azurecr.io/smart-menu-client
  tag: "1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  ip: "68.219.13.224"


volume:
  name: services-volume
  mountPath: /client
  persistentVolumeClaim: client-pvc
  storage: 2Gi


resources:
  requests:
    memory: "1Gi"
  limits:
    memory: "5Gi"