apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.persistentVolumeClaim }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storage | default "500Mi" }}