---
- hosts: all
  become: yes
  tasks:
    
# install az cli
# install kubenetes 
# install helm

- ansible.builtin.import_playbook: ./docker/installation.yaml
- ansible.builtin.import_playbook: ./jenkins/installation.yaml